version: '3'
services:

  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ceciestunmotsdepasstrescompliquepourleroot
      MYSQL_DATABASE: nicetrymates
      MYSQL_USER: limited_user
      MYSQL_PASSWORD: ceciestunmotsdepasstrescompliquepourlimited_user
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
